"""Added users table

Revision ID: 5e970ae5c3a2
Revises:
Create Date: 2026-05-14 20:53:47.475465

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e970ae5c3a2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column(
            "display_number", sa.BigInteger(), sa.Identity(always=False, start=10000, increment=1), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_number"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "user_subscription",
        sa.Column("subscriber_id", sa.Integer(), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["subscriber_id"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subscriber_id", "target_user_id"),
    )
    op.create_index(op.f("ix_user_subscription_subscriber_id"), "user_subscription", ["subscriber_id"], unique=False)
    op.create_index(op.f("ix_user_subscription_target_user_id"), "user_subscription", ["target_user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_subscription_target_user_id"), table_name="user_subscription")
    op.drop_index(op.f("ix_user_subscription_subscriber_id"), table_name="user_subscription")
    op.drop_table("user_subscription")
    op.drop_table("user")
    # ### end Alembic commands ###
