"""Added message index

Revision ID: 7482488532cd
Revises: b20b4046597e
Create Date: 2026-07-03 19:32:54.712705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7482488532cd'
down_revision: Union[str, Sequence[str], None] = 'b20b4046597e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_message_conversation_id_id', 'message', ['conversation_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_conversation_id_id', table_name='message')
    # ### end Alembic commands ###
